# Generated by Django 2.1.3 on 2018-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181127_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='Uploads/avatar.png', upload_to='Uploads/'),
        ),
    ]
