# Generated by Django 2.1.3 on 2018-11-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181130_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='AT00', max_length=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='depature_city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='flight',
            name='depature_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='depature_time',
            field=models.TimeField(max_length=50),
        ),
    ]
