# Generated by Django 2.1.3 on 2018-12-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181130_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_number',
        ),
    ]
