# Generated by Django 2.1.3 on 2018-12-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_flight_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('PD', 'Purchased'), ('RD', 'Reserved')], default='PD', max_length=200),
            preserve_default=False,
        ),
    ]
