# Generated by Django 2.1.3 on 2018-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181201_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='AT000', max_length=100),
            preserve_default=False,
        ),
    ]
